### ISSUE TITLE
Doesn't work in scripts

### ISSUE THREAD

**Issue by philastrophist** [rcaloras/bash-preexec#91]
I'd like to ship preexec with somethin I'm working on, just to run it in a script.
It doesn't work at all if I source `bash-preexec.sh` at the top of the script.

`cat my-script.sh`

```
SCRIPTLOCATION="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPTLOCATION/bash-preexec.sh"
...
preexec(){ 
	if [[ "$1" == "git"* ]]; then 
		echo -e "$Blue > $1$reset"
	fi
git status 
...
}

```

**Comment by rcaloras** [comment]
When/where are you sourcing the script? If it's just being executed bash-preexec's functions will not have any effect on your global state of your bash session. The sourcing of the containing file also should be towards the end of you bashrc/bash_profile.

**Comment by philastrophist** [comment]
I don't want `bash-preexec` to have an effect on the global state, I just want it to be used whilst the script is running. My use-case is that I want any `git` commands used within the script to echo their signature to stdout before running. That's what the `preexec` function does

**Comment by rcaloras** [comment]
@philastrophist this behavior is unsupported by bash-preexec. I'm not positive if the debug trap, how bash allows a preexec function, even can work this way in an executed script. I'd suggest either echo-ing the specific commands in the script itself since you're writing it, or I believe there's other ways to setup the script to echo all commands. 

Thanks for opening and checking out bash-preexec. Hope you can create the functionality you're trying to achieve.
